services:
  minio:
    image: minio/minio
    ports: # to try
      - "9000:9000"
      - "9001:9001"
    command: server --console-address ":9001" /data
    restart: unless-stopped
    hostname: minio
    volumes:
      - ./data:/data
    environment:
      MINIO_ROOT_USER: ${ACCESS_KEY}
      MINIO_ROOT_PASSWORD: ${SECRET_KEY}
    networks:
      - mynetwork

  nginx:
    image: nginx:alpine
    hostname: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/ssl:/etc/nginx/ssl
    ports:
      - "443:443"
    restart: unless-stopped
    depends_on:
      - minio
    networks:
      - mynetwork

networks:
  mynetwork: